version: "3.8"

services:
  api:
    image: golang:latest
    volumes:
      - ./api:/app
    working_dir: /app
    env_file: .env
    networks: 
      - backend
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: go run main.go

  site:
    image: node:latest
    volumes: 
      - ./site:/app
    working_dir: /app
    env_file: .env
    ports: 
      - "${PORT}:${PORT}"
    command: >
      bash -c "yarn install
      && yarn dev"

  mongodb:
    image: mongo:latest
    volumes: 
      - mongodb:/data/db
    env_file: .env
    networks: 
      - backend

volumes: 
  mongodb:

networks: 
  backend:
