version: "3.8"

services:
  api:
    image: golang:latest
    volumes:
      - ./api:/app
    working_dir: /app
    env_file: .env
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: go run main.go

  site:
    image: node:latest
    volumes: 
      - ./site:/app
    working_dir: /app
    env_file: .env
    ports: 
      - "${PORT}:${PORT}"
    command: >
      bash -c "yarn install
      && yarn dev"
