version: "3.8"

services:
  api:
    image: golang:latest
    volumes:
      - ./api:/app
    working_dir: /app
    env_file: .env
    networks: 
      - backend
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: go run main.go

  site:
    image: node:latest
    volumes: 
      - ./site:/app
    working_dir: /app
    env_file: .env
    ports: 
      - "${PORT}:${PORT}"
    command: >
      bash -c "yarn install
      && yarn dev"

  mongodb:
    image: mongo:latest
    volumes: 
      - mongodb:/data/db
    env_file: .env
    networks: 
      - backend

  mongo-express:
    image: mongo-express:latest
    environment: 
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DOMAIN_NAME}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks: 
      - backend
    ports: 
      - 8081:8081

volumes: 
  mongodb:

networks: 
  backend:
