version: "3.8"

services:
  api:
    image: golang:latest
    volumes:
      - ./api:/app
    working_dir: /app
    environment: 
      HOST: 0.0.0.0
      PORT: 8080
    ports: 
      - "8080:8080"
    command: go run main.go

  site:
    image: node:latest
    volumes: 
      - ./site:/app
    working_dir: /app
    environment: 
      HOST: 0.0.0.0
    ports: 
      - "3000:3000"
    command: >
      bash -c "yarn install
      && yarn dev"
