version: "3.8"

services:
  api:
    image: golang:latest
    volumes:
      - ./api:/app
    working_dir: /app
    environment: 
      HOST: ${API_HOST}
      PORT: ${API_PORT}
    ports: 
      - "${API_LOCALPORT}:${API_PORT}"
    command: go run main.go

  site:
    image: node:latest
    volumes: 
      - ./site:/app
    working_dir: /app
    environment: 
      HOST: ${HOST}
    ports: 
      - "${LOCALPORT}:3000"
    command: >
      bash -c "yarn install
      && yarn dev"
